# Mosquitto configuration file

# Allow anonymous connections
allow_anonymous false

# Default user
user mosquitto

# Listen on all interfaces, port 1883
listener 1883 0.0.0.0

# Password file location
password_file /home/nyto/Documents/git/chatnyto/flutter_app/chatnyto/mosquitto_passwd.txt


# Allow read and write access to the 'chat' topic
# topic read chat
# topic write chat
